- build.gradle
- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/controller/reactTestController.java
- src/main/java/com/codingchosun/backend/domain/Post.java
- src/main/java/com/codingchosun/backend/domain/PostUser.java
- src/main/java/com/codingchosun/backend/exception/EntityNotFoundFromDB.java
- src/main/java/com/codingchosun/backend/exception/GlobalControllerAdvice.java
- src/main/java/com/codingchosun/backend/exception/HashtagNotFoundFromDB.java
- src/main/java/com/codingchosun/backend/exception/PostNotFoundFromDB.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaHashtagRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaPostHashRepository.java
- src/main/java/com/codingchosun/backend/repository/postuserrepository/DataJpaPostUserRepository.java
- src/main/java/com/codingchosun/backend/request/RegisterPostRequest.java
- src/main/java/com/codingchosun/backend/response/ErrorResult.java
- src/main/java/com/codingchosun/backend/response/PostResponse.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/test/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepositoryTest.java
1) build.gradle에 테스트에서 log확인할수있게해주는거 추가했습니다.
2) 글 작성 구현
3) GlobalControllerAdvice에 예외처리 만들어놨습니다.
4)  HashtagRepository에 hashtagname으로 검색하는 메서드 추가했습니다.
> register post And Exception handler

- src/main/java/com/codingchosun/backend/exception/GlobalControllerAdvice.java
- src/main/java/com/codingchosun/backend/web/CatchMissingValueUtils.java
- src/main/resources/http/validate.http
> 커스텀 오류 dto로 프론트에 보내기

- src/main/java/com/codingchosun/backend/domain/Hashtag.java
- src/main/java/com/codingchosun/backend/domain/UserHash.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaUserHashRepository.java
- src/main/java/com/codingchosun/backend/service/UserUpdateService.java
- src/test/java/com/codingchosun/backend/service/UserUpdateServiceTest.java
유저 해시태그 업데이트기능 구현 테스트완료 (컨트롤러 미구현)
> Update UserUpdateService, Test, UserHash, userhashreposiroty

- src/main/resources/sql/profiletest.sql
- src/test/java/com/codingchosun/backend/service/ProfileServiceTest.java
> Update ProfileServiceTest,Create profiletest.sql

- src/main/java/com/codingchosun/backend/component/file/FileStore.java
- src/main/java/com/codingchosun/backend/controller/ImageController.java
- src/main/java/com/codingchosun/backend/controller/ProfileController.java
- src/main/java/com/codingchosun/backend/repository/commentrepository/CommentRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/HashtagRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/PostHashRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/UserHashRepository.java
- src/main/java/com/codingchosun/backend/repository/imagerepository/ImageRepository.java
- src/main/java/com/codingchosun/backend/repository/postrepository/PostRepository.java
- src/main/java/com/codingchosun/backend/repository/postuserrepository/PostUserRepository.java
- src/main/java/com/codingchosun/backend/repository/userrepository/UserRepository.java
- src/main/java/com/codingchosun/backend/service/CommentService.java
- src/main/java/com/codingchosun/backend/service/ImageService.java
- src/main/java/com/codingchosun/backend/service/LoginService.java
- src/main/java/com/codingchosun/backend/service/MyPostService.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/java/com/codingchosun/backend/service/PostUserService.java
- src/main/java/com/codingchosun/backend/service/ProfileService.java
- src/main/java/com/codingchosun/backend/service/RegisterService.java
- src/main/java/com/codingchosun/backend/service/UserUpdateService.java
- src/main/java/com/codingchosun/backend/service/ValidateService.java
- src/test/java/com/codingchosun/backend/repository/postrepository/PostRepositoryTest.java
- src/test/java/com/codingchosun/backend/service/MyPostServiceTest.java
- src/test/java/com/codingchosun/backend/service/ProfileServiceTest.java
- src/test/java/com/codingchosun/backend/service/UserUpdateServiceTest.java
> repository이름에서 DataJPA 제거

- src/main/java/com/codingchosun/backend/component/file/FileStore.java
- src/main/java/com/codingchosun/backend/controller/ImageController.java
- src/main/java/com/codingchosun/backend/controller/ProfileController.java
- src/main/java/com/codingchosun/backend/repository/commentrepository/DataJpaCommentRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaHashtagRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaPostHashRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaUserHashRepository.java
- src/main/java/com/codingchosun/backend/repository/imagerepository/DataJpaImageRepository.java
- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepository.java
- src/main/java/com/codingchosun/backend/repository/postuserrepository/DataJpaPostUserRepository.java
- src/main/java/com/codingchosun/backend/repository/userrepository/DataJpaUserRepository.java
- src/main/java/com/codingchosun/backend/service/CommentService.java
- src/main/java/com/codingchosun/backend/service/ImageService.java
- src/main/java/com/codingchosun/backend/service/LoginService.java
- src/main/java/com/codingchosun/backend/service/MyPostService.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/java/com/codingchosun/backend/service/PostUserService.java
- src/main/java/com/codingchosun/backend/service/ProfileService.java
- src/main/java/com/codingchosun/backend/service/RegisterService.java
- src/main/java/com/codingchosun/backend/service/UserUpdateService.java
- src/main/java/com/codingchosun/backend/service/ValidateService.java
- src/test/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepositoryTest.java
- src/test/java/com/codingchosun/backend/service/MyPostServiceTest.java
- src/test/java/com/codingchosun/backend/service/ProfileServiceTest.java
- src/test/java/com/codingchosun/backend/service/UserUpdateServiceTest.java
> Revert "repository이름에서 DataJPA 제거"

- src/main/java/com/codingchosun/backend/controller/LoginController.java
- src/main/java/com/codingchosun/backend/request/LoginRequest.java
- src/main/java/com/codingchosun/backend/service/LoginService.java
> Update Login param -> body

- src/main/java/com/codingchosun/backend/controller/ProfileController.java
- src/main/java/com/codingchosun/backend/request/UserUpdateRequest.java
- src/main/java/com/codingchosun/backend/service/ProfileService.java
- src/main/java/com/codingchosun/backend/service/UserUpdateService.java
- src/test/java/com/codingchosun/backend/service/ProfileServiceTest.java
> 프로필페이지 /profile/{loginId}로 변경

- src/main/java/com/codingchosun/backend/controller/CommentController.java
- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/service/CommentService.java
- src/main/java/com/codingchosun/backend/service/ImageService.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/resources/sql/peanut.sql
게시글 조회의 댓글과 이미지 링크를 page화해서 가져오게 변경
몇 몇 예외 추가
> add page to PostAndComments

- src/main/java/com/codingchosun/backend/controller/MypostController.java
- src/main/java/com/codingchosun/backend/service/MyPostService.java
- src/main/resources/sql/profiletest.sql
- src/test/java/com/codingchosun/backend/service/MyPostServiceTest.java
Mypost 컨트롤러 서비스 테스트 수정 profiletest.sql 테스트 sql 작성
> Mypost 컨트롤러 서비스 테스트 수정 profiletest.sql 테스트 sql 작성

- src/main/java/com/codingchosun/backend/service/PostService.java
글 등록할때 없는 해쉬태그를 자동으로 추가하도록 바꿨습니다.
> register post update

- src/main/java/com/codingchosun/backend/exception/invalidrequest/IsNotPostHash.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/PostControllerAdvice.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/resources/application.properties
> add properties

- src/main/java/com/codingchosun/backend/controller/ImageController.java
- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/exception/invalidrequest/AlreadyJoinedPost.java
- src/main/java/com/codingchosun/backend/exception/invalidrequest/IsNotPostAuthor.java
- src/main/java/com/codingchosun/backend/exception/invalidrequest/NotJoinedPost.java
- src/main/java/com/codingchosun/backend/exception/invalidrequest/YouAreNotAdmin.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/ImageControllerAdvice.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/PostControllerAdvice.java
- src/main/java/com/codingchosun/backend/repository/postuserrepository/DataJpaPostUserRepository.java
- src/main/java/com/codingchosun/backend/request/RemoveUserFromPostRequest.java
- src/main/java/com/codingchosun/backend/service/PostUserService.java
> add leavePost And removePostUser

- src/main/java/com/codingchosun/backend/controller/FindUserController.java
- src/main/java/com/codingchosun/backend/repository/userrepository/DataJpaUserRepository.java
- src/main/java/com/codingchosun/backend/request/FindLogginIdRequest.java
- src/main/java/com/codingchosun/backend/request/FindPasswordRequest.java
- src/main/java/com/codingchosun/backend/service/FindUserService.java
- src/main/java/com/codingchosun/backend/service/LoginService.java
아이디비밀번호찾기
아이디 찾기 이름, 이메일
비밀번호찾기 이름, 이메일, 로그인아이디
로그인시 아이디 비밀번호 같이 검증
> Create findLoginId, findpassword 로그인시 아이디 비밀번호 같이 검증, 아이디 비밀번호 찾기 기능 구현

- src/main/java/com/codingchosun/backend/controller/DeleteAccountController.java
- src/main/java/com/codingchosun/backend/service/DeleteAccountService.java
> Create DeleteAccount 회원탈퇴기능구현

- src/main/java/com/codingchosun/backend/controller/DeleteAccountController.java
> update DeleteAccountController Post말고 Get으로 아이디 삭제요청

- src/main/java/com/codingchosun/backend/controller/ProfileController.java
- src/main/java/com/codingchosun/backend/exception/invalidrequest/DeletedUserException.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/ProfileControllerAdvice.java
- src/main/java/com/codingchosun/backend/repository/userrepository/DataJpaUserRepository.java
탈퇴회원프로필들어가면 에러메세지 탈퇴한 유저입니다 body에 보냄
> 탈퇴한 회원의 프로필에 접근하지 못하도록 Exception 추가

- src/main/java/com/codingchosun/backend/exception/GlobalControllerAdvice.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/ImageControllerAdvice.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/PostControllerAdvice.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/ProfileControllerAdvice.java
> update controller advice

- src/main/java/com/codingchosun/backend/BackendApplication.java
- src/main/java/com/codingchosun/backend/component/scheduler/EventScheduler.java
- src/main/java/com/codingchosun/backend/controller/ValidateControllerV2.java
- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepository.java
- src/main/java/com/codingchosun/backend/repository/validaterepository/ValidateRepository.java
- src/main/java/com/codingchosun/backend/request/UserValidationRequest.java
- src/main/java/com/codingchosun/backend/response/UserPairDto.java
- src/main/java/com/codingchosun/backend/service/ValidateService.java
- src/main/resources/sql/peanut.sql
> add scheduler and validation

- src/main/java/com/codingchosun/backend/controller/MypostController.java
- src/main/java/com/codingchosun/backend/response/MyPostResponse.java
- src/main/java/com/codingchosun/backend/service/MyPostService.java
update mypost // mypost에서 post_id를 보내도록 수정, 참여한 모임이없을때 예외추가
> update mypost // mypost에서 post_id를 보내도록 수정, 참여한 모임이없을때 예외추가

- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaHashtagRepository.java
- src/main/java/com/codingchosun/backend/repository/hashtagrepository/DataJpaPostHashRepository.java
- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepository.java
> add repository

- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepositoryImpl.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/resources/http/validate.http
> 검색기능 수정, 포스트 경로 수정

- src/main/java/com/codingchosun/backend/constants/DeleteConstants.java
- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/service/PostService.java
> add delete post

- src/main/java/com/codingchosun/backend/response/ImageResponse.java
> update image path

- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepository.java
- src/main/java/com/codingchosun/backend/repository/postrepository/DataJpaPostRepositoryImpl.java
- src/main/java/com/codingchosun/backend/service/PostService.java
- src/main/resources/http/validate.http
> 게시물 검색시 공백이면 전체 게시물 출력

- src/main/java/com/codingchosun/backend/controller/LoginController.java
- src/main/java/com/codingchosun/backend/web/SameSiteCookieConfiguration.java
> session 없음오류 수정

- src/main/java/com/codingchosun/backend/exception/invalidrequest/AlreadyValidated.java
- src/main/java/com/codingchosun/backend/exception/localcontrolleradvice/ValidateControllerAdvice.java
- src/main/java/com/codingchosun/backend/service/ValidateService.java
평가하면 유저 스코어에 반영되도록 수정.
중복 평가시 예외처리함
> add user score

- build.gradle
- src/main/java/com/codingchosun/backend/domain/User.java
- src/main/java/com/codingchosun/backend/exception/ExistLoginId.java
- src/main/java/com/codingchosun/backend/request/RegisterUserRequest.java
- src/main/java/com/codingchosun/backend/security/AccountDetailService.java
- src/main/java/com/codingchosun/backend/security/AccountDetailSupplier.java
- src/main/java/com/codingchosun/backend/service/SignUpService.java
- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> Security 도입하여 password암호화 로그인 구현,

- src/main/java/com/codingchosun/backend/controller/CommentController.java
- src/main/java/com/codingchosun/backend/controller/ImageController.java
- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/controller/ValidateControllerV2.java
@Login -> @AuthenticationPrincipal으로 수정함
> @Login -> @AuthenticationPrincipal

- src/main/java/com/codingchosun/backend/controller/LoginController.java
- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> 로그인컨트롤러 다시만들기

- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> 커스텀페이지 사용설정

- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> cors설정 테스트

- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> cors설정 테스트2

- src/main/java/com/codingchosun/backend/controller/PostController.java
> fix method name

- src/main/java/com/codingchosun/backend/controller/LoginCheckController.java
> get login user

- src/main/java/com/codingchosun/backend/controller/MypostController.java
> update mypost + security

- src/main/java/com/codingchosun/backend/service/UserUpdateService.java
> 비밀번호수정시 암호화

- src/main/java/com/codingchosun/backend/controller/PostController.java
- src/main/java/com/codingchosun/backend/request/RegisterPostRequest.java
- src/main/java/com/codingchosun/backend/web/SecurityConfig.java
> plus 9 hours

- src/main/java/com/codingchosun/backend/service/MyPostService.java
마이포스트를 포스트아이디의 내림차순으로 정렬한 후 프론트로
> 마이포스트 최신순으로 정렬

- src/main/java/com/codingchosun/backend/request/PostUpdateRequest.java
- src/main/java/com/codingchosun/backend/service/PostService.java
> fix edit post tags

- src/main/java/com/codingchosun/backend/service/SignUpService.java
> 기본 점수 50으로 변경

- src/main/java/com/codingchosun/backend/service/user/LoginService.java
> fix: 탈퇴한 회원이 로그인할 경우 예외를 던지도록 수정

- src/main/java/com/codingchosun/backend/dto/request/ProfileResponse.java
- src/main/java/com/codingchosun/backend/dto/request/UserUpdateRequest.java
- src/main/java/com/codingchosun/backend/service/user/ProfileService.java
이메일, 성별 수정 삭제
닉네임, 새 비밀번호 제한 추가
> fix: 회원 정보 수정 request 필드 수정
